config/routes.rb
PhotoGallery::Application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  root 'static_pages#home'

  resources :galleries, only: [:show]
  resources :posts, only: [:show]
  resources :notes, only: [:index]

  namespace :api, defaults: { format: 'json' } do
    resources :galleries, only: [] do
      resources :images, only: [:show], controller: 'galleries/images'
    end
  end
end

app/models/ckeditor/asset.rb
class Ckeditor::Asset < ActiveRecord::Base
  include Ckeditor::Orm::ActiveRecord::AssetBase

  delegate :url, :current_path, :content_type, :to => :data

  validates_presence_of :data
end

app/models/ckeditor/attachment_file.rb
class Ckeditor::AttachmentFile < Ckeditor::Asset
  mount_uploader :data, CkeditorAttachmentFileUploader, :mount_on => :data_file_name

  def url_thumb
    @url_thumb ||= Ckeditor::Utils.filethumb(filename)
  end
end

app/models/ckeditor/picture.rb
class Ckeditor::Picture < Ckeditor::Asset
  mount_uploader :data, CkeditorPictureUploader, :mount_on => :data_file_name

  def url_content
    url(:content)
  end
end

app/models/concerns/adminable/gallery.rb
module Adminable::Gallery
  extend ActiveSupport::Concern

  included do
    rails_admin do
      list do
        field :name
        field :created_at
      end
      # edit do
        # field :name
      # end
    end
  end
end

app/models/concerns/adminable/gallery/image.rb
module Adminable::Gallery::Image
  extend ActiveSupport::Concern

  included do
    rails_admin do
      parent ::Gallery

      list do
        field :id
        field :src
        field :gallery
        field :created_at

        items_per_page 5
      end
    end
  end
end

app/models/concerns/adminable/note.rb
module Adminable::Note
  extend ActiveSupport::Concern

  included do
    rails_admin do
      list do
        field :title
        field :link
        field :created_at
      end

      edit do
        field :title
        field :content, :ck_editor
        field :image
        field :link
      end
    end
  end
end

app/models/concerns/adminable/post.rb
module Adminable::Post
  extend ActiveSupport::Concern

  included do
    rails_admin do
      list do
        field :title
        field :created_at
      end

      edit do
        field :title
        field :content, :ck_editor
        field :image
      end
    end
  end
end

app/models/concerns/adminable/quote.rb
module Adminable::Quote
  extend ActiveSupport::Concern

  included do
    rails_admin do
      list do
        field :author
        field :content
      end
  
      edit do
        field :author
        field :content, :ck_editor
      end
    end
  end
end

app/models/gallery.rb
class Gallery < PhotoGallery::Base
  include Adminable::Gallery

  has_many :images, class_name: '::Gallery::Image', dependent: :destroy

  def to_param
    name.downcase
  end
end

app/models/gallery/image.rb
class Gallery::Image < PhotoGallery::Base
  include Adminable::Gallery::Image

	belongs_to :gallery

  delegate :name, to: :gallery, prefix: true, allow_nil: true

	mount_uploader :src, ::GalleryImageUploader

  def cache_key
    [
      id,
      updated_at
    ].join '_'
  end
end

app/models/note.rb
class Note < PhotoGallery::Base
  include Adminable::Note

  mount_uploader :image, NoteImageUploader

  def to_param
    [id, title.parameterize].join '-'
  end
end

app/models/portfolio_logo.rb
class PortfolioLogo < PhotoGallery::Base
  mount_uploader :src, PortfolioLogoUploader
end

app/models/post.rb
class Post < PhotoGallery::Base
  include Adminable::Post

  mount_uploader :image, PostImageUploader

  def to_param
    [id, title.parameterize].join '-'
  end
end

app/models/quote.rb
class Quote < PhotoGallery::Base
  include Adminable::Quote

  class << self
    def day_qoute
      quote = Rails.cache.fetch day_qoute_cache_key
      unless quote
        quote = Quote.all.sample
        cache_quote quote
      end
      quote
      quote = Quote.all.sample
    end

    def day_qoute_cache_key
      'Quote.day_qoute'
    end

    def cache_quote(quote)
      Rails.cache.write(
        day_qoute_cache_key,
        quote,
        day_qoute_expires
      )
    end

    def day_qoute_expires
      time = Time.now
      {
        expires_in: (time.end_of_day - time)
      }
    end
  end
end

app/models/user.rb
class User < PhotoGallery::Base
end

app/controllers/api/application_controller.rb
class Api::ApplicationController < ActionController::Base

end

app/controllers/api/galleries/images_controller.rb
module Api
  class Galleries::ImagesController < ApplicationController
    before_action :set_gallery

    def show
      @image = ::Gallery::Image.find_by_id params[:id]
      # exit
      # if @gallery
      # @image
      # = @gallery.images.find_by_id params[:id]
      #
      # end
    end

    private

    def set_gallery
      # @gallery = ::Gallery.find_by_id params[:gallery_id]
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :header_view

  private

  def header_view
    @header_top_menu_view = View::Header::TopMenu.new params
  end
end

app/controllers/galleries_controller.rb
class GalleriesController < ApplicationController
  before_action :set_gallery, only: [:show]

  # def index

  # end

  def show
    name = params[:id]
    @images =
      if name == 'all'
        Gallery::Image.order(updated_at: :desc)
      else
        @gallery.images
      end
    # @images = @images.order(updated_at: :desc).page(params[:page]).per(50)
    @image_ids = @images.select(:id).order(updated_at: :desc).page(params[:page]).per(50).pluck :id
    @galleries = Gallery.all
    @show_gallery = true
  end

  private

  def set_gallery
    name = params[:id]
    @gallery =
      if name == 'all'
        Gallery.new
      else
        Gallery.where('LOWER(name) = ?', name).first
      end

  end
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  def index
    @notes = Note.order(updated_at: :desc).page(params[:page]).per(5)

    @posts = Post.order(updated_at: :desc).page(params[:page]).per(3)
    @menu_posts = Post.order(updated_at: :desc).first(3)
    @quote = Quote.day_qoute
    @galleries = Gallery.includes(:images).all
    @note = Note.last
    @logo = PortfolioLogo.all.sample
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show]
  def show
    @posts = Post.order(updated_at: :desc).page(params[:page]).per(3)
    @menu_posts = Post.order(updated_at: :desc).first(3)
    @quote = Quote.day_qoute
    @galleries = Gallery.includes(:images).all
    @note = Note.last
    @logo = PortfolioLogo.all.sample
  end

  private

  def set_post
    @post = Post.find_by_id(params[:id])
  end
end

app/controllers/static_pages_controller.rb

class StaticPagesController < ApplicationController
  def home
    @posts = Post.order(updated_at: :desc).page(params[:page]).per(3)
    @menu_posts = Post.order(updated_at: :desc).first(3)
    @quote = Quote.day_qoute
    @galleries = Gallery.includes(:images).all
    @note = Note.last
    @logo = PortfolioLogo.all.sample
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/galleries/_gallery.html.erb
<div class="gamma-container gamma-loading" id="gamma-container">
  <ul class="gamma-gallery">
    <%= render partial: 'galleries/image_li', collection: images, as: :image %>
  </ul>
   <div class="gamma-overlay"></div>
</div>

app/views/galleries/_image.html.erb
<%= image_tag image.src, alt: @gallery.name %>

app/views/galleries/_image2.html.erb
<li>
  <div data-alt="img03" data-description="<h3>Sky high</h3>" data-max-width="1800" data-max-height="1350">
    <div data-src="<%= image.src.xxxlarge %>" data-min-width="1300"></div>
    <div data-src="<%= image.src.xxlarge %>" data-min-width="1000"></div>
    <div data-src="<%= image.src.xlarge %>" data-min-width="700"></div>
    <div data-src="<%= image.src.large %>" data-min-width="300"></div>
    <div data-src="<%= image.src.medium %>" data-min-width="200"></div>
    <div data-src="<%= image.src.small %>" data-min-width="140"></div>
    <div data-src="<%= image.src.xsmall %>"></div>
    <noscript>
      <img src="<%= image.src.xsmall %>" alt="img03"/>
    </noscript>
  </div>
</li>

app/views/galleries/_image_li.html.erb
<li>
  <div data-alt="img03"
    data-description="<h3>Sky high</h3>"
    data-max-width="1800"
    data-max-height="1350">
    <div data-src="<%= image.src.xxxlarge %>" data-min-width="1300"></div>
    <div data-src="<%= image.src.xxlarge %>" data-min-width="1000"></div>
    <div data-src="<%= image.src.xlarge %>" data-min-width="700"></div>
    <div data-src="<%= image.src.large %>" data-min-width="300"></div>
    <div data-src="<%= image.src.medium %>" data-min-width="200"></div>
    <div data-src="<%= image.src.small %>" data-min-width="140"></div>
    <div data-src="<%= image.src.xsmall %>"></div>
    <noscript>
      <img src="<%= image.src.xsmall %>" alt="img03"/>
    </noscript>
  </div>
</li>

app/views/galleries/_li.html.erb
<li>
  <%= link_to gallery, rel: 'external', class: 'test'  do %>
      <span><%= gallery.name %></span>
    <% end %>
</li>

app/views/galleries/_ul.html.erb
<ul class="category">

  <li>
    <%= link_to gallery_path('all'), rel: 'external' do %>
      <span>ALL</span>
    <% end %>
  </li>

  <%= render partial: 'galleries/li', collection: galleries, as: :gallery %>
</ul>

app/views/galleries/show.html.erb
<% content_for :main_class, 'gallery-main' %>
<div class="top_menu_wrapper ">
  <%= render 'galleries/topmenu/ul', galleries: @galleries %>
</div>


<div class="gallery_wrapper ">
<gallery
  gallery-id="<%= @gallery.id %>"
  image-ids="<%= @image_ids %>" >
</gallery>
</div>

<div class="clear"></div>

<div class="galary_pagination  margin-left-20">
  <% #= paginate @images %>
</div>

app/views/galleries/topmenu/_li.html.erb
<li>
  <%= link_to gallery.name, gallery, rel: 'external', target: '_blank', class: 'top_menu_a' %>
</li>

app/views/galleries/topmenu/_ul.html.erb
<ul class="top_menu_category">

  <li>
    <%= link_to 'ALL', gallery_path('all'), rel: 'external', target: '_blank', class: 'top_menu_a' %>
  </li>

  <%= render partial: 'galleries/topmenu/li', collection: galleries, as: :gallery %>
</ul> 

app/views/notes/_note.html.erb
<div class="blog-content-left-i margin-bottom-30">
  <div class="blog-content-left-i-title padding-bottom-20 title">
    <%= link_to note.link do %>
    <% note.title %>
    <% end %>
  </div>

  <div class="line padding-bottom-30"></div>

  <div class="image post-photo margin-right-20 float-left">
    <%= link_to note.link do %>
    <%  image_tag note.image %>
    <% end %>
  </div>

  <div class="content text">
    <%= note.content.html_safe %>
    <%= I18n.l note.created_at, format: '%B %d, %Y' %>
    <%= I18n.l note.updated_at, format: '%B %d, %Y' %>
  </div>

  <div class="clear margin-bottom-30"></div>
  <div class="line padding-bottom-30"></div>
  <%= link_to 'Посмотреть подробно', note.link, class: 'link-more', target: '_blank' %>

  <div class="clear"></div>

</div>
  

app/views/notes/index.html.erb
<div class="wrapper">
  <div class="blog-content-left float-left"> 
    <%= render partial: 'notes/note', collection: @notes %>
    <div class="clear"></div>
    <%= paginate @notes %> 
  </div>

  <%= render 'layouts/right_block',
        galleries: @galleries,
        posts: @menu_posts,
        note: @note,
        logo: @logo,
        quote: @quote %>

  <div class="clear"></div>
</div>


app/views/notes/menu/_item.html.erb
<h2 class="padding-bottom-20">Последние открытия</h2>
<div class="date">
 <%= I18n.l note.created_at, format: '%d %B, %Y' %>
</div>
<div class="line margin-20-0 "></div>
<div class="blog-content-right-i-opens-wrapper">
  <div class="blog-content-right-i-opens-photo float-left">
    <%= link_to note.link, target: '_blank'  do %>
    <%  image_tag note.image, class: 'blog-content-right-i-opens-photo-i' %>
    <% end %>
  </div>
  <%= link_to  note.title, note.link, class: 'blog-content-right-i-opens-a', target: '_blank' %>

  <div>
    <%= sanitize(truncate_html(note.content, length: 180), tags: %w(br ul li p)) %>
  </div>
  <div class="clear-right"></div>
</div>

<div class="line margin-20-0 "></div>

<%= link_to 'Все открытия', notes_path, class: 'link-more' %>
<div class="clear-right"></div>
 

app/views/posts/_post.html.erb
<div class="blog-content-left-i margin-bottom-30">
  <h1 class="blog-content-left-i-title padding-bottom-20 title">
   <%= link_to post.title, post %>
  </h1>
  <div class="date padding-bottom-20"><%= I18n.l post.created_at, format: '%d %B, %Y' %></div>
  <div class="line padding-bottom-30"></div>
  <div class="post-photo margin-bottom-30">
    <%= image_tag post.image %>
  </div>
  <div class="text margin-bottom-30">
    <%= sanitize(truncate_html(post.content, length: 430), tags: %w(br ul li p)) %>
  </div>
  <div class="line padding-bottom-30"></div>
  <%= link_to 'Показать полностью', post, class: 'link-more' %>
  <div class="clear"></div>
</div> 
 

app/views/posts/menu/_item.html.erb
<li>
  <%= link_to post.title, post, rel: 'external' %>
</li>

app/views/posts/menu/_list.html.erb
<h2>Последние заметки</h2>
<ul class="collection">
  <%= render partial: 'posts/menu/item', collection: posts, as: 'post' %>
</ul>

app/views/posts/show.html.erb
<div class="wrapper post">
  <div class="blog-content-left float-left">
    <div class="blog-content-left-i">
      <div class="blog-content-left-i-title padding-bottom-20 title"><%= @post.title %></div>
      <div class="created_at date padding-bottom-20"><%= I18n.l @post.created_at, format: '%d %B, %Y' %></div>
      <div class="line padding-bottom-30"></div>
      <div class="image post-photo margin-bottom-30"><%= image_tag @post.image %></div>
      <div class="content text"><%= @post.content.html_safe %></div>
    </div>
  </div>

<%= render 'layouts/right_block',
  galleries: @galleries,
  posts: @posts,
  note: @note,
  logo: @logo,
  quote: @quote %>

  <div class="clear"></div>

</div>
 